/**
 * Export utilities for ModelEditor component
 *
 * Provides functionality to export models to various formats including
 * ESM JSON, LaTeX, MathML, and other representations as required by the
 * task specification.
 */

import type { Model, Expression } from '../types.js';

/**
 * Export formats supported by the ModelEditor
 */
export type ExportFormat = 'esm-json' | 'latex' | 'mathml' | 'python' | 'julia' | 'markdown';

/**
 * Export options for different formats
 */
export interface ExportOptions {
  /** Include comments in exported code */
  includeComments?: boolean;
  /** Pretty-print the output */
  prettyPrint?: boolean;
  /** Include metadata (citations, descriptions) */
  includeMetadata?: boolean;
  /** Mathematical notation style for LaTeX/MathML */
  mathStyle?: 'display' | 'inline';
}

/**
 * Export model to various formats
 */
export function exportModel(model: Model, format: ExportFormat, options: ExportOptions = {}): string {
  const opts: Required<ExportOptions> = {
    includeComments: true,
    prettyPrint: true,
    includeMetadata: true,
    mathStyle: 'display',
    ...options
  };

  switch (format) {
    case 'esm-json':
      return exportToESMJSON(model, opts);
    case 'latex':
      return exportToLaTeX(model, opts);
    case 'mathml':
      return exportToMathML(model, opts);
    case 'python':
      return exportToPython(model, opts);
    case 'julia':
      return exportToJulia(model, opts);
    case 'markdown':
      return exportToMarkdown(model, opts);
    default:
      throw new Error(`Unsupported export format: ${format}`);
  }
}

/**
 * Export model to ESM JSON format
 */
function exportToESMJSON(model: Model, options: Required<ExportOptions>): string {
  if (options.prettyPrint) {
    return JSON.stringify(model, null, 2);
  }
  return JSON.stringify(model);
}

/**
 * Export model to LaTeX format
 */
function exportToLaTeX(model: Model, options: Required<ExportOptions>): string {
  let latex = '';

  if (options.includeComments && options.includeMetadata && model.reference?.citation) {
    latex += `% ${model.reference.citation}\n`;
    if (model.reference.notes) {
      latex += `% Notes: ${model.reference.notes}\n`;
    }
    latex += '\n';
  }

  latex += '\\begin{align}\n';

  // Export equations
  model.equations.forEach((eq, index) => {
    const lhsLatex = expressionToLaTeX(eq.lhs);
    const rhsLatex = expressionToLaTeX(eq.rhs);

    if (options.includeComments) {
      latex += `  % Equation ${index + 1}\n`;
    }

    latex += `  ${lhsLatex} &= ${rhsLatex}`;

    if (index < model.equations.length - 1) {
      latex += ' \\\\\n';
    } else {
      latex += '\n';
    }
  });

  latex += '\\end{align}\n';

  // Add variable definitions if requested
  if (options.includeMetadata) {
    latex += '\n% Variable Definitions:\n';
    Object.entries(model.variables).forEach(([name, variable]) => {
      latex += `% ${name}: ${variable.description || 'No description'}`;
      if (variable.units) {
        latex += ` [${variable.units}]`;
      }
      latex += '\n';
    });
  }

  return latex;
}

/**
 * Export model to MathML format
 */
function exportToMathML(model: Model, options: Required<ExportOptions>): string {
  let mathml = '';

  if (options.includeMetadata && model.reference?.citation) {
    mathml += `<!-- ${model.reference.citation} -->\n`;
  }

  mathml += '<math xmlns="http://www.w3.org/1998/Math/MathML">\n';

  if (options.mathStyle === 'display') {
    mathml += '  <mtable>\n';

    model.equations.forEach((eq, index) => {
      mathml += '    <mtr>\n';
      mathml += '      <mtd>\n';
      mathml += `        ${expressionToMathML(eq.lhs)}\n`;
      mathml += '      </mtd>\n';
      mathml += '      <mtd>\n';
      mathml += '        <mo>=</mo>\n';
      mathml += '      </mtd>\n';
      mathml += '      <mtd>\n';
      mathml += `        ${expressionToMathML(eq.rhs)}\n`;
      mathml += '      </mtd>\n';
      mathml += '    </mtr>\n';
    });

    mathml += '  </mtable>\n';
  } else {
    // Inline style
    model.equations.forEach((eq, index) => {
      if (index > 0) mathml += '  <mo>,</mo>\n';
      mathml += `  ${expressionToMathML(eq.lhs)}\n`;
      mathml += '  <mo>=</mo>\n';
      mathml += `  ${expressionToMathML(eq.rhs)}\n`;
    });
  }

  mathml += '</math>\n';

  return mathml;
}

/**
 * Export model to Python code
 */
function exportToPython(model: Model, options: Required<ExportOptions>): string {
  let python = '';

  if (options.includeComments) {
    python += '# ESM Model exported to Python\n';
    if (options.includeMetadata && model.reference?.citation) {
      python += `# Citation: ${model.reference.citation}\n`;
    }
    python += '# Generated by ESM ModelEditor\n\n';
  }

  python += 'import numpy as np\nfrom scipy.integrate import solve_ivp\n\n';

  // Define parameters
  python += 'def create_model_parameters():\n';
  python += '    """Define model parameters"""\n';
  python += '    params = {}\n';

  Object.entries(model.variables)
    .filter(([_, variable]) => variable.type === 'parameter')
    .forEach(([name, variable]) => {
      const defaultValue = variable.default ?? 1.0;
      python += `    params['${name}'] = ${defaultValue}`;
      if (options.includeComments && variable.description) {
        python += `  # ${variable.description}`;
        if (variable.units) {
          python += ` [${variable.units}]`;
        }
      }
      python += '\n';
    });

  python += '    return params\n\n';

  // Define ODEs
  python += 'def model_ode(t, y, params):\n';
  python += '    """Model ODE system"""\n';

  const stateVars = Object.entries(model.variables)
    .filter(([_, variable]) => variable.type === 'state')
    .map(([name]) => name);

  stateVars.forEach((name, index) => {
    python += `    ${name} = y[${index}]\n`;
  });

  python += '    \n    # ODEs\n';
  python += '    dydt = np.zeros(len(y))\n';

  let stateIndex = 0;
  model.equations.forEach((eq) => {
    if (typeof eq.lhs === 'object' && eq.lhs.op === 'D') {
      const variable = eq.lhs.args[0] as string;
      const rhsPython = expressionToPython(eq.rhs);
      python += `    dydt[${stateIndex}] = ${rhsPython}`;
      if (options.includeComments) {
        python += `  # d${variable}/dt`;
      }
      python += '\n';
      stateIndex++;
    }
  });

  python += '    \n    return dydt\n';

  return python;
}

/**
 * Export model to Julia code
 */
function exportToJulia(model: Model, options: Required<ExportOptions>): string {
  let julia = '';

  if (options.includeComments) {
    julia += '# ESM Model exported to Julia\n';
    if (options.includeMetadata && model.reference?.citation) {
      julia += `# Citation: ${model.reference.citation}\n`;
    }
    julia += '# Generated by ESM ModelEditor\n\n';
  }

  julia += 'using DifferentialEquations\n\n';

  // Define parameters
  julia += 'function create_model_parameters()\n';
  const paramEntries = Object.entries(model.variables)
    .filter(([_, variable]) => variable.type === 'parameter');

  if (paramEntries.length > 0) {
    julia += '    params = (\n';
    paramEntries.forEach(([name, variable], index) => {
      const defaultValue = variable.default ?? 1.0;
      julia += `        ${name} = ${defaultValue}`;
      if (index < paramEntries.length - 1) julia += ',';
      if (options.includeComments && variable.description) {
        julia += `  # ${variable.description}`;
        if (variable.units) {
          julia += ` [${variable.units}]`;
        }
      }
      julia += '\n';
    });
    julia += '    )\n';
  } else {
    julia += '    params = ()\n';
  }

  julia += '    return params\nend\n\n';

  // Define ODEs
  julia += 'function model_ode!(du, u, p, t)\n';

  const stateVars = Object.entries(model.variables)
    .filter(([_, variable]) => variable.type === 'state')
    .map(([name]) => name);

  stateVars.forEach((name, index) => {
    julia += `    ${name} = u[${index + 1}]\n`;
  });

  julia += '    \n    # ODEs\n';

  let stateIndex = 1;
  model.equations.forEach((eq) => {
    if (typeof eq.lhs === 'object' && eq.lhs.op === 'D') {
      const variable = eq.lhs.args[0] as string;
      const rhsJulia = expressionToJulia(eq.rhs);
      julia += `    du[${stateIndex}] = ${rhsJulia}`;
      if (options.includeComments) {
        julia += `  # d${variable}/dt`;
      }
      julia += '\n';
      stateIndex++;
    }
  });

  julia += 'end\n';

  return julia;
}

/**
 * Export model to Markdown format
 */
function exportToMarkdown(model: Model, options: Required<ExportOptions>): string {
  let markdown = '';

  // Title and metadata
  markdown += '# Model Documentation\n\n';

  if (options.includeMetadata && model.reference?.citation) {
    markdown += `**Citation:** ${model.reference.citation}\n\n`;
    if (model.reference.notes) {
      markdown += `**Notes:** ${model.reference.notes}\n\n`;
    }
  }

  // Variables section
  markdown += '## Variables\n\n';

  const variablesByType = {
    state: [] as Array<[string, any]>,
    parameter: [] as Array<[string, any]>,
    observed: [] as Array<[string, any]>
  };

  Object.entries(model.variables).forEach(([name, variable]) => {
    variablesByType[variable.type].push([name, variable]);
  });

  ['state', 'parameter', 'observed'].forEach(type => {
    const vars = variablesByType[type as keyof typeof variablesByType];
    if (vars.length > 0) {
      markdown += `### ${type.charAt(0).toUpperCase() + type.slice(1)} Variables\n\n`;
      markdown += '| Variable | Units | Default | Description |\n';
      markdown += '|----------|-------|---------|-------------|\n';

      vars.forEach(([name, variable]) => {
        const units = variable.units || '-';
        const defaultValue = variable.default !== undefined ? String(variable.default) : '-';
        const description = variable.description || '-';
        markdown += `| \`${name}\` | ${units} | ${defaultValue} | ${description} |\n`;
      });

      markdown += '\n';
    }
  });

  // Equations section
  markdown += '## Equations\n\n';

  model.equations.forEach((eq, index) => {
    const lhsMarkdown = expressionToMarkdown(eq.lhs);
    const rhsMarkdown = expressionToMarkdown(eq.rhs);
    markdown += `${index + 1}. $${lhsMarkdown} = ${rhsMarkdown}$\n\n`;
  });

  // Events section (if present)
  if (model.discrete_events?.length || model.continuous_events?.length) {
    markdown += '## Events\n\n';

    if (model.discrete_events?.length) {
      markdown += '### Discrete Events\n\n';
      model.discrete_events.forEach(event => {
        markdown += `**${event.name}**\n`;
        markdown += `- Trigger: ${JSON.stringify(event.trigger)}\n`;
        if (event.affects?.length) {
          markdown += '- Effects:\n';
          event.affects.forEach(affect => {
            const lhs = expressionToMarkdown(affect.lhs);
            const rhs = expressionToMarkdown(affect.rhs);
            markdown += `  - $${lhs} = ${rhs}$\n`;
          });
        }
        markdown += '\n';
      });
    }

    if (model.continuous_events?.length) {
      markdown += '### Continuous Events\n\n';
      model.continuous_events.forEach(event => {
        markdown += `**${event.name}**\n`;
        markdown += '- Conditions:\n';
        event.conditions.forEach(condition => {
          markdown += `  - $${expressionToMarkdown(condition)}$\n`;
        });
        if (event.affects?.length) {
          markdown += '- Effects:\n';
          event.affects.forEach(affect => {
            const lhs = expressionToMarkdown(affect.lhs);
            const rhs = expressionToMarkdown(affect.rhs);
            markdown += `  - $${lhs} = ${rhs}$\n`;
          });
        }
        markdown += '\n';
      });
    }
  }

  return markdown;
}

/**
 * Convert expression to LaTeX
 */
function expressionToLaTeX(expr: Expression): string {
  if (typeof expr === 'string') {
    // Handle chemical species with subscripts
    return expr.replace(/([A-Za-z]+)(\d+)/g, '\\mathrm{$1_{$2}}');
  }

  if (typeof expr === 'number') {
    return expr.toString();
  }

  if (typeof expr === 'object' && expr && 'op' in expr) {
    const { op, args } = expr;

    switch (op) {
      case '+':
        return args.map(arg => expressionToLaTeX(arg)).join(' + ');
      case '-':
        if (args.length === 1) {
          return `-${expressionToLaTeX(args[0])}`;
        }
        return args.map((arg, i) =>
          i === 0 ? expressionToLaTeX(arg) : `- ${expressionToLaTeX(arg)}`
        ).join(' ');
      case '*':
        return args.map(arg => {
          const latex = expressionToLaTeX(arg);
          return typeof arg === 'object' && arg.op === '+' || arg.op === '-' ? `(${latex})` : latex;
        }).join(' \\cdot ');
      case '/':
        return `\\frac{${expressionToLaTeX(args[0])}}{${expressionToLaTeX(args[1])}}`;
      case '^':
        return `${expressionToLaTeX(args[0])}^{${expressionToLaTeX(args[1])}}`;
      case 'D':
        const variable = expressionToLaTeX(args[0]);
        const wrt = expr.wrt || 't';
        return `\\frac{d${variable}}{d${wrt}}`;
      default:
        return `\\text{${op}}(${args.map(arg => expressionToLaTeX(arg)).join(', ')})`;
    }
  }

  return String(expr);
}

/**
 * Convert expression to MathML
 */
function expressionToMathML(expr: Expression): string {
  if (typeof expr === 'string') {
    return `<mi>${expr}</mi>`;
  }

  if (typeof expr === 'number') {
    return `<mn>${expr}</mn>`;
  }

  if (typeof expr === 'object' && expr && 'op' in expr) {
    const { op, args } = expr;

    switch (op) {
      case '+':
        return args.map((arg, i) =>
          i === 0 ? expressionToMathML(arg) : `<mo>+</mo>${expressionToMathML(arg)}`
        ).join('');
      case '-':
        if (args.length === 1) {
          return `<mo>-</mo>${expressionToMathML(args[0])}`;
        }
        return args.map((arg, i) =>
          i === 0 ? expressionToMathML(arg) : `<mo>-</mo>${expressionToMathML(arg)}`
        ).join('');
      case '*':
        return args.map(arg => expressionToMathML(arg)).join('<mo>⋅</mo>');
      case '/':
        return `<mfrac><mrow>${expressionToMathML(args[0])}</mrow><mrow>${expressionToMathML(args[1])}</mrow></mfrac>`;
      case '^':
        return `<msup><mrow>${expressionToMathML(args[0])}</mrow><mrow>${expressionToMathML(args[1])}</mrow></msup>`;
      case 'D':
        const variable = expressionToMathML(args[0]);
        const wrt = expr.wrt || 't';
        return `<mfrac><mrow><mi>d</mi>${variable}</mrow><mrow><mi>d</mi><mi>${wrt}</mi></mrow></mfrac>`;
      default:
        return `<mi>${op}</mi><mo>(</mo>${args.map(arg => expressionToMathML(arg)).join('<mo>,</mo>')}<mo>)</mo>`;
    }
  }

  return `<mi>${String(expr)}</mi>`;
}

/**
 * Convert expression to Python code
 */
function expressionToPython(expr: Expression): string {
  if (typeof expr === 'string') {
    return expr;
  }

  if (typeof expr === 'number') {
    return expr.toString();
  }

  if (typeof expr === 'object' && expr && 'op' in expr) {
    const { op, args } = expr;

    switch (op) {
      case '+':
        return `(${args.map(arg => expressionToPython(arg)).join(' + ')})`;
      case '-':
        if (args.length === 1) {
          return `(-${expressionToPython(args[0])})`;
        }
        return `(${args.map((arg, i) =>
          i === 0 ? expressionToPython(arg) : ` - ${expressionToPython(arg)}`
        ).join('')})`;
      case '*':
        return `(${args.map(arg => expressionToPython(arg)).join(' * ')})`;
      case '/':
        return `(${expressionToPython(args[0])} / ${expressionToPython(args[1])})`;
      case '^':
        return `(${expressionToPython(args[0])} ** ${expressionToPython(args[1])})`;
      case 'exp':
        return `np.exp(${expressionToPython(args[0])})`;
      case 'log':
        return `np.log(${expressionToPython(args[0])})`;
      case 'sin':
        return `np.sin(${expressionToPython(args[0])})`;
      case 'cos':
        return `np.cos(${expressionToPython(args[0])})`;
      default:
        return `${op}(${args.map(arg => expressionToPython(arg)).join(', ')})`;
    }
  }

  return String(expr);
}

/**
 * Convert expression to Julia code
 */
function expressionToJulia(expr: Expression): string {
  if (typeof expr === 'string') {
    return expr;
  }

  if (typeof expr === 'number') {
    return expr.toString();
  }

  if (typeof expr === 'object' && expr && 'op' in expr) {
    const { op, args } = expr;

    switch (op) {
      case '+':
        return `(${args.map(arg => expressionToJulia(arg)).join(' + ')})`;
      case '-':
        if (args.length === 1) {
          return `(-${expressionToJulia(args[0])})`;
        }
        return `(${args.map((arg, i) =>
          i === 0 ? expressionToJulia(arg) : ` - ${expressionToJulia(arg)}`
        ).join('')})`;
      case '*':
        return `(${args.map(arg => expressionToJulia(arg)).join(' * ')})`;
      case '/':
        return `(${expressionToJulia(args[0])} / ${expressionToJulia(args[1])})`;
      case '^':
        return `(${expressionToJulia(args[0])} ^ ${expressionToJulia(args[1])})`;
      case 'exp':
        return `exp(${expressionToJulia(args[0])})`;
      case 'log':
        return `log(${expressionToJulia(args[0])})`;
      case 'sin':
        return `sin(${expressionToJulia(args[0])})`;
      case 'cos':
        return `cos(${expressionToJulia(args[0])})`;
      default:
        return `${op}(${args.map(arg => expressionToJulia(arg)).join(', ')})`;
    }
  }

  return String(expr);
}

/**
 * Convert expression to Markdown LaTeX
 */
function expressionToMarkdown(expr: Expression): string {
  // For markdown, we use LaTeX syntax
  return expressionToLaTeX(expr);
}

/**
 * Get available export formats
 */
export function getAvailableFormats(): ExportFormat[] {
  return ['esm-json', 'latex', 'mathml', 'python', 'julia', 'markdown'];
}

/**
 * Get file extension for export format
 */
export function getFileExtension(format: ExportFormat): string {
  const extensions: Record<ExportFormat, string> = {
    'esm-json': 'json',
    'latex': 'tex',
    'mathml': 'xml',
    'python': 'py',
    'julia': 'jl',
    'markdown': 'md'
  };
  return extensions[format];
}

/**
 * Download exported model as file
 */
export function downloadExport(content: string, filename: string, mimeType: string = 'text/plain'): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.click();

  URL.revokeObjectURL(url);
}