"""
ESM Format - Earth System Model Serialization Format

A Python package for handling Earth System Model serialization and mathematical expressions.
"""

from .types import (
    Expr,
    ExprNode,
    Equation,
    AffectEquation,
    ModelVariable,
    Model,
    Species,
    Parameter,
    Reaction,
    ReactionSystem,
    ContinuousEvent,
    DiscreteEvent,
    FunctionalAffect,
    DiscreteEventTrigger,
    DataLoader,
    DataLoaderType,
    Operator,
    OperatorType,
    CouplingEntry,
    Domain,
    Solver,
    Reference,
    Metadata,
    EsmFile,
)
from .parse import load, SchemaValidationError, UnsupportedVersionError
from .serialize import save
from .validation import validate, ValidationResult, ValidationError
from .verification import (
    MathematicalVerifier,
    VerificationResult,
    VerificationReport,
    VerificationStatus,
    verify_reaction_system,
    verify_model,
    compute_stoichiometric_matrix,
)
from .simulation import (
    simulate,
    simulate_with_discrete_events,
    SimulationResult,
    SimulationError,
)
from .data_loaders import (
    NetCDFLoader,
    JSONLoader,
    create_data_loader,
)
from .data_loader_registry import (
    DataLoaderRegistry,
    get_registry,
    register_loader,
    create_auto_loader,
    detect_loader_type,
)
from .operator_registry import (
    OperatorRegistry,
    get_registry as get_operator_registry,
    register_operator,
    create_operator,
    create_operator_by_name,
    list_operators_by_type,
    has_operator,
)
from .coupling_graph import (
    CouplingGraph,
    CouplingNode,
    CouplingEdge,
    NodeType,
    DependencyInfo,
    construct_coupling_graph,
    validate_coupling_graph,
    ScopedReference,
    ScopedReferenceResolver,
    resolve_coupling_dependencies,
    build_execution_order_from_dependencies,
)
from .hierarchical_scope_resolution import (
    HierarchicalScopeResolver,
    ScopeInfo,
    VariableResolution,
    create_enhanced_scoped_reference,
)
from .placeholder_expansion import (
    expand_placeholder,
    expand_multiple_placeholders,
    validate_placeholder_expansion,
    get_placeholder_variables,
    create_expansion_template,
    ExpansionContext,
    CircularReferenceError,
    PlaceholderExpansionError,
)

__version__ = "0.1.0"
__all__ = [
    "Expr",
    "ExprNode",
    "Equation",
    "AffectEquation",
    "ModelVariable",
    "Model",
    "Species",
    "Parameter",
    "Reaction",
    "ReactionSystem",
    "ContinuousEvent",
    "DiscreteEvent",
    "FunctionalAffect",
    "DiscreteEventTrigger",
    "DataLoader",
    "DataLoaderType",
    "Operator",
    "OperatorType",
    "CouplingEntry",
    "Domain",
    "Solver",
    "Reference",
    "Metadata",
    "EsmFile",
    "load",
    "save",
    "validate",
    "ValidationResult",
    "ValidationError",
    "SchemaValidationError",
    "UnsupportedVersionError",
    "MathematicalVerifier",
    "VerificationResult",
    "VerificationReport",
    "VerificationStatus",
    "verify_reaction_system",
    "verify_model",
    "compute_stoichiometric_matrix",
    "simulate",
    "simulate_with_discrete_events",
    "SimulationResult",
    "SimulationError",
    "NetCDFLoader",
    "JSONLoader",
    "create_data_loader",
    "DataLoaderRegistry",
    "get_registry",
    "register_loader",
    "create_auto_loader",
    "detect_loader_type",
    "OperatorRegistry",
    "get_operator_registry",
    "register_operator",
    "create_operator",
    "create_operator_by_name",
    "list_operators_by_type",
    "has_operator",
    "CouplingGraph",
    "CouplingNode",
    "CouplingEdge",
    "NodeType",
    "DependencyInfo",
    "construct_coupling_graph",
    "validate_coupling_graph",
    "ScopedReference",
    "ScopedReferenceResolver",
    "resolve_coupling_dependencies",
    "build_execution_order_from_dependencies",
    "HierarchicalScopeResolver",
    "ScopeInfo",
    "VariableResolution",
    "create_enhanced_scoped_reference",
    "expand_placeholder",
    "expand_multiple_placeholders",
    "validate_placeholder_expansion",
    "get_placeholder_variables",
    "create_expansion_template",
    "ExpansionContext",
    "CircularReferenceError",
    "PlaceholderExpansionError",
]