"""
ESM Format - Earth System Model Serialization Format

A Python package for handling Earth System Model serialization and mathematical expressions.
"""

from .types import (
    Expr,
    ExprNode,
    Equation,
    AffectEquation,
    ModelVariable,
    Model,
    Species,
    Parameter,
    Reaction,
    ReactionSystem,
    ContinuousEvent,
    DiscreteEvent,
    FunctionalAffect,
    DiscreteEventTrigger,
    DataLoader,
    DataLoaderType,
    Operator,
    OperatorType,
    CouplingEntry,
    Domain,
    TemporalDomain,
    SpatialDimension,
    CoordinateTransform,
    InitialCondition,
    InitialConditionType,
    BoundaryCondition,
    BoundaryConditionType,
    Solver,
    Reference,
    Metadata,
    EsmFile,
)
from .parse import load, SchemaValidationError, UnsupportedVersionError
from .serialize import save
from .validation import validate, ValidationResult, ValidationError
from .expression import free_variables, contains, evaluate, simplify
from .substitute import substitute, substitute_in_model, substitute_in_reaction_system
from .verification import (
    MathematicalVerifier,
    VerificationResult,
    VerificationReport,
    VerificationStatus,
    verify_reaction_system,
    verify_model,
    compute_stoichiometric_matrix,
)
from .simulation import (
    simulate,
    simulate_with_discrete_events,
    SimulationResult,
    SimulationError,
)
from .data_loaders import (
    NetCDFLoader,
    JSONLoader,
    BinaryLoader,
    create_data_loader,
)
from .data_loader_registry import (
    DataLoaderRegistry,
    get_registry,
    register_loader,
    create_auto_loader,
    detect_loader_type,
)
from .operator_registry import (
    OperatorRegistry,
    get_registry as get_operator_registry,
    register_operator,
    create_operator,
    create_operator_by_name,
    list_operators_by_type,
    has_operator,
)
from .operator_dispatch import (
    OperatorDispatcher,
    TypeSignature,
    OperatorOverload,
    get_dispatcher,
    dispatch_operator,
    register_operator_overload,
    get_operator_overloads,
    get_dispatch_info,
)
from .coupling_graph import (
    CouplingGraph,
    CouplingNode,
    CouplingEdge,
    NodeType,
    DependencyInfo,
    construct_coupling_graph,
    validate_coupling_graph,
    ScopedReference,
    ScopedReferenceResolver,
    resolve_coupling_dependencies,
    build_execution_order_from_dependencies,
)
from .coupling_iteration import (
    CouplingIterator,
    ConvergenceConfig,
    RelaxationConfig,
    AccelerationConfig,
    IterationState,
    CouplingResult,
    ConvergenceMethod,
    RelaxationMethod,
    AccelerationMethod,
    create_default_coupling_iterator,
    create_adaptive_coupling_iterator,
)
from .coupling_error_handling import (
    RobustCouplingIterator,
    CouplingErrorType,
    RecoveryStrategy,
    ExecutionMode,
    CouplingErrorContext,
    CouplingError,
    RecoveryConfig,
    DiagnosticReport,
    CouplingErrorAnalyzer,
    CouplingRecoveryManager,
    create_robust_coupling_iterator,
    create_fault_tolerant_iterator,
)
from .hierarchical_scope_resolution import (
    HierarchicalScopeResolver,
    ScopeInfo,
    VariableResolution,
    create_enhanced_scoped_reference,
)
from .placeholder_expansion import (
    expand_placeholder,
    expand_multiple_placeholders,
    validate_placeholder_expansion,
    get_placeholder_variables,
    create_expansion_template,
    ExpansionContext,
    CircularReferenceError,
    PlaceholderExpansionError,
)
from .boundary_conditions import (
    BoundaryConditionProcessor,
    BoundaryProcessorConfig,
    BoundaryConstraint,
    BoundaryLocationError,
    BoundaryValueError,
    create_dirichlet_boundary,
    create_neumann_boundary,
    create_periodic_boundary,
    validate_domain_boundary_consistency,
)
from .time_synchronization import (
    TimeSynchronizer,
    TimeStep,
    TimePoint,
    TimeSeries,
    ComponentTimeState,
    TimeInterpolationMethod,
    TimeExtrapolationMethod,
    TimeAlignmentStrategy,
    synchronize_coupled_system,
    create_subcycling_synchronizer,
    validate_time_synchronization_config,
)
from .error_handling import (
    ErrorCode,
    Severity,
    ErrorContext,
    FixSuggestion,
    ESMError,
    ErrorCollector,
    ESMErrorFactory,
    PerformanceProfiler,
    InteractiveErrorExplorer,
    profile_operation,
    get_profiler,
    setup_error_logging,
)
from .temporal_operators import (
    DerivativeOperator,
    IntegralOperator,
    TemporalAveragingOperator,
    TimeSteppingOperator,
    TemporalScheme,
    IntegrationMethod,
    TemporalOperatorConfig,
)
from .interpolation_operators import (
    LinearInterpolationOperator,
    CubicInterpolationOperator,
    SplineInterpolationOperator,
    GridInterpolationOperator,
    InterpolationConfig,
    BaseInterpolationOperator,
    create_interpolation_operator,
)
from .reactions import (
    derive_odes,
    stoichiometric_matrix,
    substrate_matrix,
    product_matrix,
)
from .graph import (
    component_graph,
    expression_graph,
    to_dot,
    to_mermaid,
    to_json_graph,
    Graph,
    GraphNode,
    GraphEdge,
    ComponentNode,
    VariableNode,
    CouplingEdge,
    DependencyEdge,
)
from .units import (
    validate_units,
    convert_units,
    UnitValidator,
    UnitValidationResult,
    UnitConversionResult,
)
from .edit import (
    ESMEditor,
    EditOperation,
    EditResult,
    add_model_to_file,
    add_variable_to_model,
    rename_variable_in_model,
)
from .display import (
    explore,
    ESMExplorer,
)
from .codegen import (
    to_julia_code,
    to_python_code,
)

__version__ = "0.1.0"
__all__ = [
    "Expr",
    "ExprNode",
    "Equation",
    "AffectEquation",
    "ModelVariable",
    "Model",
    "Species",
    "Parameter",
    "Reaction",
    "ReactionSystem",
    "ContinuousEvent",
    "DiscreteEvent",
    "FunctionalAffect",
    "DiscreteEventTrigger",
    "DataLoader",
    "DataLoaderType",
    "Operator",
    "OperatorType",
    "CouplingEntry",
    "Domain",
    "TemporalDomain",
    "SpatialDimension",
    "CoordinateTransform",
    "InitialCondition",
    "InitialConditionType",
    "BoundaryCondition",
    "BoundaryConditionType",
    "BoundaryConditionProcessor",
    "BoundaryProcessorConfig",
    "BoundaryConstraint",
    "BoundaryLocationError",
    "BoundaryValueError",
    "create_dirichlet_boundary",
    "create_neumann_boundary",
    "create_periodic_boundary",
    "validate_domain_boundary_consistency",
    "Solver",
    "Reference",
    "Metadata",
    "EsmFile",
    "load",
    "save",
    "validate",
    "ValidationResult",
    "ValidationError",
    "SchemaValidationError",
    "UnsupportedVersionError",
    "MathematicalVerifier",
    "VerificationResult",
    "VerificationReport",
    "VerificationStatus",
    "verify_reaction_system",
    "verify_model",
    "compute_stoichiometric_matrix",
    "simulate",
    "simulate_with_discrete_events",
    "SimulationResult",
    "SimulationError",
    "NetCDFLoader",
    "JSONLoader",
    "BinaryLoader",
    "create_data_loader",
    "DataLoaderRegistry",
    "get_registry",
    "register_loader",
    "create_auto_loader",
    "detect_loader_type",
    "OperatorRegistry",
    "get_operator_registry",
    "register_operator",
    "create_operator",
    "create_operator_by_name",
    "list_operators_by_type",
    "has_operator",
    # Operator dispatch system
    "OperatorDispatcher",
    "TypeSignature",
    "OperatorOverload",
    "get_dispatcher",
    "dispatch_operator",
    "register_operator_overload",
    "get_operator_overloads",
    "get_dispatch_info",
    "CouplingGraph",
    "CouplingNode",
    "CouplingEdge",
    "NodeType",
    "DependencyInfo",
    "construct_coupling_graph",
    "validate_coupling_graph",
    "ScopedReference",
    "ScopedReferenceResolver",
    "resolve_coupling_dependencies",
    "build_execution_order_from_dependencies",
    # Coupling iteration and convergence control
    "CouplingIterator",
    "ConvergenceConfig",
    "RelaxationConfig",
    "AccelerationConfig",
    "IterationState",
    "CouplingResult",
    "ConvergenceMethod",
    "RelaxationMethod",
    "AccelerationMethod",
    "create_default_coupling_iterator",
    "create_adaptive_coupling_iterator",
    # Coupling error handling and recovery
    "RobustCouplingIterator",
    "CouplingErrorType",
    "RecoveryStrategy",
    "ExecutionMode",
    "CouplingErrorContext",
    "CouplingError",
    "RecoveryConfig",
    "DiagnosticReport",
    "CouplingErrorAnalyzer",
    "CouplingRecoveryManager",
    "create_robust_coupling_iterator",
    "create_fault_tolerant_iterator",
    "HierarchicalScopeResolver",
    "ScopeInfo",
    "VariableResolution",
    "create_enhanced_scoped_reference",
    "expand_placeholder",
    "expand_multiple_placeholders",
    "validate_placeholder_expansion",
    "get_placeholder_variables",
    "create_expansion_template",
    "ExpansionContext",
    "CircularReferenceError",
    "PlaceholderExpansionError",
    "TimeSynchronizer",
    "TimeStep",
    "TimePoint",
    "TimeSeries",
    "ComponentTimeState",
    "TimeInterpolationMethod",
    "TimeExtrapolationMethod",
    "TimeAlignmentStrategy",
    "synchronize_coupled_system",
    "create_subcycling_synchronizer",
    "validate_time_synchronization_config",
    "free_variables",
    "contains",
    "evaluate",
    "simplify",
    "substitute",
    "substitute_in_model",
    "substitute_in_reaction_system",
    # Error handling and diagnostics
    "ErrorCode",
    "Severity",
    "ErrorContext",
    "FixSuggestion",
    "ESMError",
    "ErrorCollector",
    "ESMErrorFactory",
    "PerformanceProfiler",
    "InteractiveErrorExplorer",
    "profile_operation",
    "get_profiler",
    "setup_error_logging",
    # Temporal operators
    "DerivativeOperator",
    "IntegralOperator",
    "TemporalAveragingOperator",
    "TimeSteppingOperator",
    "TemporalScheme",
    "IntegrationMethod",
    "TemporalOperatorConfig",
    # Interpolation operators
    "LinearInterpolationOperator",
    "CubicInterpolationOperator",
    "SplineInterpolationOperator",
    "GridInterpolationOperator",
    "InterpolationConfig",
    "BaseInterpolationOperator",
    "create_interpolation_operator",
    # Reaction system analysis
    "derive_odes",
    "stoichiometric_matrix",
    "substrate_matrix",
    "product_matrix",
    # Graph representations
    "component_graph",
    "expression_graph",
    "to_dot",
    "to_mermaid",
    "to_json_graph",
    "Graph",
    "GraphNode",
    "GraphEdge",
    "ComponentNode",
    "VariableNode",
    "CouplingEdge",
    "DependencyEdge",
    # Unit validation
    "validate_units",
    "convert_units",
    "UnitValidator",
    "UnitValidationResult",
    "UnitConversionResult",
    # Editing operations
    "ESMEditor",
    "EditOperation",
    "EditResult",
    "add_model_to_file",
    "add_variable_to_model",
    "rename_variable_in_model",
    # Jupyter integration
    "explore",
    "ESMExplorer",
    # Code generation
    "to_julia_code",
    "to_python_code",
]